### ISSUE TITLE
NameError (uninitialized constant Net::HTTPGenericRequest::METHOD):

### ISSUE THREAD

**Issue by masterkain** [martinbtt/net-http-spy#1]
Hello,
I found a gem having issues:

```
gem 'omniauth-foursquare'

NameError (uninitialized constant Net::HTTPGenericRequest::METHOD):
net-http-spy (0.2.1) lib/net-http-spy.rb:33:in `request'
faraday (0.7.6) lib/faraday/adapter/net_http.rb:61:in `call'
faraday (0.7.6) lib/faraday/request/url_encoded.rb:14:in `call'
faraday (0.7.6) lib/faraday/connection.rb:210:in `run_request'
/Users/kain/.rvm/gems/ruby-1.9.3-p0/bundler/gems/oauth2-8fba38201ecd/lib/oauth2/client.rb:88:in `request'
/Users/kain/.rvm/gems/ruby-1.9.3-p0/bundler/gems/oauth2-8fba38201ecd/lib/oauth2/client.rb:128:in `get_token'
/Users/kain/.rvm/gems/ruby-1.9.3-p0/bundler/gems/oauth2-8fba38201ecd/lib/oauth2/strategy/auth_code.rb:29:in `get_token'
omniauth-oauth2 (1.0.0) lib/omniauth/strategies/oauth2.rb:77:in `build_access_token'
omniauth-oauth2 (1.0.0) lib/omniauth/strategies/oauth2.rb:61:in `callback_phase'
omniauth (1.0.2) lib/omniauth/strategy.rb:204:in `callback_call'
omniauth (1.0.2) lib/omniauth/strategy.rb:166:in `call!'
omniauth (1.0.2) lib/omniauth/strategy.rb:148:in `call'
omniauth (1.0.2) lib/omniauth/strategy.rb:168:in `call!'
omniauth (1.0.2) lib/omniauth/strategy.rb:148:in `call'
omniauth (1.0.2) lib/omniauth/strategy.rb:168:in `call!'
omniauth (1.0.2) lib/omniauth/strategy.rb:148:in `call'
omniauth (1.0.2) lib/omniauth/strategy.rb:168:in `call!'
omniauth (1.0.2) lib/omniauth/strategy.rb:148:in `call'
sass (3.1.12) lib/sass/plugin/rack.rb:54:in `call'
warden (1.1.0) lib/warden/manager.rb:35:in `block in call'
warden (1.1.0) lib/warden/manager.rb:34:in `catch'
warden (1.1.0) lib/warden/manager.rb:34:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.1) lib/rack/etag.rb:23:in `call'
rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/cookies.rb:338:in `call'
activerecord (3.2.0) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:443:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.0) lib/active_support/callbacks.rb:405:in `_run__809047665242244114__call__4399012686297305678__callbacks'
activesupport (3.2.0) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.0) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.0) lib/rails/rack/logger.rb:26:in `call_app'
railties (3.2.0) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.1) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.0) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.1) lib/rack/lock.rb:15:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/static.rb:53:in `call'
railties (3.2.0) lib/rails/engine.rb:479:in `call'
railties (3.2.0) lib/rails/application.rb:220:in `call'
railties (3.2.0) lib/rails/railtie/configurable.rb:30:in `method_missing'
thin (1.3.1) lib/thin/stats.rb:24:in `block in call'
thin (1.3.1) lib/thin/stats.rb:33:in `log'
thin (1.3.1) lib/thin/stats.rb:24:in `call'
thin (1.3.1) lib/thin/connection.rb:80:in `block in pre_process'
thin (1.3.1) lib/thin/connection.rb:78:in `catch'
thin (1.3.1) lib/thin/connection.rb:78:in `pre_process'
thin (1.3.1) lib/thin/connection.rb:53:in `process'
thin (1.3.1) lib/thin/connection.rb:38:in `receive_data'
eventmachine (0.12.10) lib/eventmachine.rb:256:in `run_machine'
eventmachine (0.12.10) lib/eventmachine.rb:256:in `run'
thin (1.3.1) lib/thin/backends/base.rb:61:in `start'
thin (1.3.1) lib/thin/server.rb:159:in `start'
thin (1.3.1) lib/thin/controllers/controller.rb:86:in `start'
thin (1.3.1) lib/thin/runner.rb:185:in `run_command'
thin (1.3.1) lib/thin/runner.rb:151:in `run!'
thin (1.3.1) bin/thin:6:in `<top (required)>'
/Users/kain/.rvm/gems/ruby-1.9.3-p0/bin/thin:19:in `load'
/Users/kain/.rvm/gems/ruby-1.9.3-p0/bin/thin:19:in `<main>'
```

**Comment by masterkain** [comment]
Fixed in my fork: https://github.com/masterkain/net-http-spy/commit/58dc111094a61884c1ab699a09aa1ccc77cf7472 but not sure if it's retrocompatible.

**Comment by assembler** [comment]
+1

**Comment by msaspence** [comment]
+1

**Comment by jimworm** [comment]
+1

**Comment by maccman** [comment]
+1

**Comment by maccman** [comment]
Would love to see a fix for this.
